#!/bin/bash 
ATA="10.62.150"
fileEnd=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)

for (( j=2; j<=31; j++ ))
do    
  
  cd /var/log/rsyslog/$ATA.$j
  echo "" > messages.log

  for (( i=0; i<=23; i++ ))
  do
    vState[$i]=1
  done

  mState[$j]=${vState[*]}

done

while [ "2" -gt "1" ]
do
   
    for (( j=2; j<=31; j++ ))
    do
      sleep 0.1
      cd /var/log/rsyslog/$ATA.$j
      source ramais.sh   
      filefirt[$j]=$(cat messages.log | grep -i Vinetic::setLineState | cut -c 95-110 | wc -l)

      if [ "${filefirt[j]}" -gt "${fileEnd[j]}" ]
      then
          fileEnd[$j]=${filefirt[j]}
          
          for (( i=0; i<=15; i++ ))
          do
            log[$i]=$(cat messages.log | grep -i Vinetic::setLineState | cut -c 95-110 | grep -e "0:$i " | tail -n1 )
            port[$i]=$(echo ${log[i]} | awk '{print $2}' | cut -d ":" -f2)
            state[$i]=$(echo ${log[i]} | awk '{print $4}')

            vState=(${mState[j]})

            if [ "${vState[i]}" != "${state[i]}" ]
            then
                echo "UPDATE ramais.ramais SET status = '${state[i]}' WHERE ramal = '${ramal[i]}' " | mysql -uroot -p123456
                 
                 vState[$i]=${state[i]}
                 mState[$j]=${vState[*]}
            fi
          done

          for (( i=0; i<=7; i++ ))
          do
            cont=$[16 + $i]
            log[$cont]=$(cat messages.log | grep -i Vinetic::setLineState | cut -c 95-110 | grep -e "1:$i " | tail -n1 )
            port[$cont]=$(echo ${log[cont]} | awk '{print $2}' | cut -d ":" -f2)
            state[$cont]=$(echo ${log[cont]} | awk '{print $4}')
    
            vState=(${mState[j]})

            if [ "${vState[cont]}" != "${state[cont]}" ]
            then
                echo "UPDATE ramais.ramais SET status = '${state[cont]}' WHERE ramal = '${ramal[cont]}' " | mysql -uroot -p123456
                
                 vState[$cont]=${state[cont]}
                 mState[$j]=${vState[*]}
            fi
          done
        fi      
    done 
done
