#!/bin/bash

# Coloque o arquivo no diretorio /bin
# Para criar um repositorio digite o comanto abaixo
# mkdir meuNovoRepo
# cd meuNovoRepo
# git-create meuNovoRepo UserGit 

repo_name=$1
user=$2

curl -u $user https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
git init
echo "# $repo_name" >> README.md
git add README.md
echo -n "Digite a sua mensatem de commit: "
read msg
git commit -m "$msg"
git remote add origin git@github.com:sojnar/$repo_name.git
git push -u origin master 

